### ISSUE TITLE
Compatibility with NUS guidelines: margin size

### ISSUE THREAD

**Issue by RatulSaha** [saurabhg17/SPhdThesis#2]
The class file mentions: `left=1.25in, right=1in, top=1in, bottom=1in` passed to geometry package.

The guideline mentions 

> The left and right margins should be 1 1⁄2 inches. The top and bottom margins should not
> be less than 1 inch each.

Could you please confirm that the class file adheres to the guideline?

**Comment by saurabhg17** [comment]
Dear Ratul,

I thought it strictly adheres to the guidelines but I guess it doesn’t. I will update the Github repository accordingly.

I didn’t like all the guidelines set forth by NUS and I didn’t formatted my thesis according to them. Specifically, I didn’t used double spacing (I find it too ugly) and the margins were bit smaller (1 ½ is too much wasted space). I added switches for line spacing and few others before publishing the template so that if others want they can follow NUS guidelines. I think I might have missed about margin. 

Regards,

Saurabh
